version: "3.3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: livecity_rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=ruha
      - RABBITMQ_DEFAULT_PASS=gcSrYfKz
      - RABBITMQ_DEFAULT_VHOST=livecity
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./deploy/rabbitmq/data/:/var/lib/rabbitmq/
      - ./deploy/rabbitmq/log/:/var/log/rabbitmq/

  backend:
    build: ./backend/
    image: livecity_backend
    restart: on-failure
    container_name: livecity_backend
    env_file:
      - ./backend/.env
    command: bash -c "python manage.py makemigrations --noinput && python manage.py migrate --noinput && python manage.py loaddata users && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"