# Generated by Django 4.1.2 on 2022-11-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spgz',
            name='key',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='fileupdate',
            name='type_file',
            field=models.CharField(choices=[('sn', 'sn'), ('smeta', 'smeta'), ('spgz', 'spgz'), ('spgz_key', 'spgz_key'), ('tz', 'tz')], max_length=10),
        ),
    ]
