# Generated by Django 4.1.2 on 2022-11-06 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeta',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sn',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='okei',
            name='short_name',
            field=models.CharField(max_length=200),
        ),
    ]
