# Generated by Django 4.1.2 on 2022-11-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_smeta_json_data_sn_json_data_alter_okei_short_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sn',
            name='json_data',
        ),
        migrations.AddField(
            model_name='snsection',
            name='json_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
