# Generated by Django 4.1.2 on 2022-10-30 18:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPGZ',
            fields=[
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=2000)),
            ],
            managers=[
                ('objcets', django.db.models.manager.Manager()),
            ],
        ),
    ]
