# Generated by Django 4.1.2 on 2022-11-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sn_json_data_snsection_json_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smeta',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='snsection',
            name='json_data',
        ),
    ]
