# Generated by Django 4.1.2 on 2022-10-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_kpgz'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='kpgz',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='kpgz',
            name='code',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
