# Generated by Django 4.1.2 on 2022-10-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_okei_alter_kpgz_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OKPD',
            fields=[
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'ОКПД',
                'verbose_name_plural': 'ОКПД',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OKPD2',
            fields=[
                ('code', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'ОКПД2',
                'verbose_name_plural': 'ОКПД2',
                'ordering': ['code'],
            },
        ),
    ]
