# Generated by Django 4.1.2 on 2022-11-06 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_spgz_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmetaRowStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fasstext_percent', models.FloatField(default=0.0)),
                ('key_phrases_percent', models.FloatField(default=0.0)),
                ('levenst_ratio', models.FloatField(default=0.0)),
                ('is_key', models.BooleanField(default=False)),
                ('fasttext_spgz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fasttext_stats', to='core.spgz')),
                ('key_phrases_spgz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_phrases_stats', to='core.spgz')),
                ('sn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.smetarow')),
            ],
        ),
        migrations.CreateModel(
            name='SmetaRowStatWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('percent', models.FloatField(default=0.0)),
                ('smeta_row_stat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stat_words', to='core.smetarowstat')),
            ],
        ),
    ]
