# Generated by Django 4.1.2 on 2022-11-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_smetarowstat_smetarowstatwords'),
    ]

    operations = [
        migrations.AddField(
            model_name='smetarowstat',
            name='smeta_row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.smetarow'),
        ),
        migrations.AlterField(
            model_name='smetarowstat',
            name='sn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='core.sn'),
        ),
    ]
