# Generated by Django 4.1.2 on 2022-11-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_smetarowstat_smeta_row_alter_smetarowstat_sn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smetarowstat',
            options={'verbose_name': 'Смета:Расширенная строка', 'verbose_name_plural': 'Смета: Расчширенные строки'},
        ),
    ]
