# Generated by Django 4.1.2 on 2022-10-31 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_okei_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_file', models.IntegerField(choices=[(0, 'SN'), (1, 'Smeta')], default=0)),
                ('file', models.FileField(upload_to='files')),
                ('date_upload', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ref', models.CharField(max_length=250, verbose_name='Тип сбоника')),
                ('advance', models.IntegerField(default=0, verbose_name='Дополнение')),
                ('coef_ref', models.IntegerField(default=0, verbose_name='Номер сборника')),
                ('coef_date', models.DateField(verbose_name='Дата сборника')),
                ('sum', models.FloatField(default=0.0, verbose_name='Итого')),
                ('tax', models.FloatField(default=0.0, verbose_name='НДС')),
                ('sum_with_tax', models.FloatField(default=0.0, verbose_name='Итого с НДС')),
                ('sum_with_ko', models.FloatField(default=0.0, verbose_name='Итого с коэф. фин. обеспеч.')),
            ],
        ),
        migrations.CreateModel(
            name='SNRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Шифр')),
                ('num', models.IntegerField(default=0, verbose_name='Номер п/п')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('count', models.FloatField(default=0.0, verbose_name='Количество')),
                ('sum', models.FloatField(default=0.0, verbose_name='Итого')),
                ('okei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.okei')),
            ],
        ),
        migrations.CreateModel(
            name='SNSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('sum', models.FloatField(default=0.0, verbose_name='Итого')),
                ('sn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.sn')),
            ],
        ),
        migrations.CreateModel(
            name='SNSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование')),
                ('sum', models.FloatField(default=0.0, verbose_name='Итого')),
                ('sn_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='core.snsection')),
            ],
        ),
        migrations.CreateModel(
            name='SNSubRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('count', models.FloatField(default=0.0, verbose_name='Количество')),
                ('amount', models.FloatField(default=1.0, verbose_name='Цена за единицу')),
                ('coef_correct', models.FloatField(default=1.0, verbose_name='Корректировочный коэф')),
                ('coef_winter', models.FloatField(default=1.0, verbose_name='Зимний коэф')),
                ('coef_recalc', models.FloatField(default=1.0, verbose_name='Коэф. пересчета')),
                ('sum_basic', models.FloatField(default=0.0, verbose_name='Затраты в базисном уровне')),
                ('sum_current', models.FloatField(default=0.0, verbose_name='Затраты в текущем уровне')),
                ('okei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.okei')),
                ('sn_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrows', to='core.snrow')),
            ],
        ),
        migrations.AddField(
            model_name='snrow',
            name='sn_subsection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.snsubsection'),
        ),
    ]
