# Generated by Django 4.1.2 on 2022-10-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_fileupdate_sn_snrow_snsection_snsubsection_snsubrow_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupdate',
            name='type_file',
            field=models.CharField(choices=[('SN', 'SN'), ('Smeta', 'Smeta')], default=0, max_length=100),
        ),
    ]
