# Generated by Django 4.1.2 on 2022-11-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_smetarowstat_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='smetarow',
            name='is_key',
            field=models.BooleanField(default=False, verbose_name='Ключевая позиция'),
        ),
    ]
