# Generated by Django 4.1.2 on 2022-11-01 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_fileupdate_type_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileupdate',
            options={'verbose_name': 'Файл обновления справочника', 'verbose_name_plural': 'Файлы обновления справочника'},
        ),
    ]
