# Generated by Django 4.1.2 on 2022-11-02 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_fileupdate_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snrow',
            name='okei',
        ),
        migrations.RemoveField(
            model_name='snsubrow',
            name='okei',
        ),
        migrations.AddField(
            model_name='snrow',
            name='ei',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.okei'),
        ),
        migrations.AddField(
            model_name='snsubrow',
            name='ei',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.okei'),
        ),
        migrations.AlterField(
            model_name='fileupdate',
            name='type_file',
            field=models.CharField(choices=[('SN', 'SN'), ('Smeta', 'Smeta'), ('SPGZ', 'SPGZ')], default=0, max_length=100),
        ),
        migrations.CreateModel(
            name='SPGZ',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.TextField(verbose_name='Наименование')),
                ('ei', models.ManyToManyField(related_name='spgz', to='core.okei')),
                ('kpgz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spgz', to='core.kpgz')),
                ('okpd', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spgz', to='core.okpd')),
                ('okpd2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spgz', to='core.okpd2')),
            ],
        ),
    ]
