# Generated by Django 4.1.2 on 2022-11-07 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_smetarowstat_options_smetarowstat_key_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smeta',
            options={'ordering': ['-id'], 'verbose_name': 'Смета', 'verbose_name_plural': 'Сметы'},
        ),
    ]
