# Generated by Django 4.1.2 on 2022-11-08 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_smeta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeta',
            name='status_file',
            field=models.IntegerField(choices=[(0, 'Загружен'), (1, 'Создается в БД'), (2, 'Обрабатывается'), (3, 'Готов')], default=0, verbose_name='Статус сметы'),
        ),
    ]
