# Generated by Django 4.1.2 on 2022-11-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_snrow_okei_remove_snsubrow_okei_snrow_ei_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sn',
            options={'verbose_name': 'СН и ТСН', 'verbose_name_plural': 'СН и ТСН'},
        ),
        migrations.AlterModelOptions(
            name='snrow',
            options={'verbose_name': 'СН и ТСН: Строка', 'verbose_name_plural': 'СН и ТСН: Строки'},
        ),
        migrations.AlterModelOptions(
            name='snsection',
            options={'verbose_name': 'СН и ТСН: Раздел', 'verbose_name_plural': 'СН и ТСН: Разделы'},
        ),
        migrations.AlterModelOptions(
            name='snsubrow',
            options={'verbose_name': 'СН и ТСН: Статья затрат', 'verbose_name_plural': 'СН и ТСН: Статьи затрат'},
        ),
        migrations.AlterModelOptions(
            name='snsubsection',
            options={'verbose_name': 'СН и ТСН: Подраздел', 'verbose_name_plural': 'СН и ТСН: Подразделы'},
        ),
        migrations.AlterModelOptions(
            name='spgz',
            options={'verbose_name': 'СПГЗ', 'verbose_name_plural': 'СПГЗ'},
        ),
        migrations.AlterField(
            model_name='fileupdate',
            name='type_file',
            field=models.CharField(choices=[('sn', 'sn'), ('smeta', 'smeta'), ('spgz', 'spgz')], default=0, max_length=100),
        ),
    ]
