# Generated by Django 4.1.2 on 2022-11-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_sn_options_alter_snrow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupdate',
            name='type_update',
            field=models.CharField(choices=[('full', 'full'), ('add', 'add')], default='full', max_length=10),
        ),
        migrations.AlterField(
            model_name='fileupdate',
            name='type_file',
            field=models.CharField(choices=[('sn', 'sn'), ('smeta', 'smeta'), ('spgz', 'spgz')], max_length=10),
        ),
    ]
