# Generated by Django 4.1.2 on 2022-11-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_smeta_status_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='smetarow',
            name='sum_keys',
            field=models.FloatField(default=0.0, verbose_name='Ключевая сумма'),
        ),
        migrations.AlterField(
            model_name='smeta',
            name='status_file',
            field=models.IntegerField(choices=[(0, 'Загружен файл'), (1, 'Загружен в БД'), (2, 'Обрабатывается'), (3, 'Готов')], default=0, verbose_name='Статус сметы'),
        ),
        migrations.AlterField(
            model_name='smeta',
            name='type_ref',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Тип сбоника'),
        ),
    ]
