# Generated by Django 4.1.2 on 2022-11-03 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_fileupdate_type_update_alter_fileupdate_type_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='TZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.AlterField(
            model_name='fileupdate',
            name='type_file',
            field=models.CharField(choices=[('sn', 'sn'), ('smeta', 'smeta'), ('spgz', 'spgz'), ('tz', 'tz')], max_length=10),
        ),
        migrations.CreateModel(
            name='TZRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpgz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tz', to='core.kpgz')),
                ('spgz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tz', to='core.spgz')),
                ('tz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='core.tz')),
            ],
        ),
    ]
