# Generated by Django 4.1.2 on 2022-11-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_smetarow_sum_keys_alter_smeta_status_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smetarow',
            options={'ordering': ['num'], 'verbose_name': 'Смета: Строка', 'verbose_name_plural': 'Смета: Строки'},
        ),
    ]
