# Generated by Django 4.1.2 on 2022-11-08 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_smetarow_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='smeta',
            name='tz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smetes', to='core.tz'),
        ),
    ]
