# Generated by Django 4.1.2 on 2022-11-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_tz_alter_fileupdate_type_file_tzrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sn',
            name='advance',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Дополнение'),
        ),
        migrations.AlterField(
            model_name='sn',
            name='coef_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата сборника'),
        ),
        migrations.AlterField(
            model_name='sn',
            name='coef_ref',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Номер сборника'),
        ),
    ]
