# Generated by Django 4.1.2 on 2022-11-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_sn_advance_alter_sn_coef_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tz',
            options={'verbose_name': 'ТЗ', 'verbose_name_plural': 'ТЗ'},
        ),
        migrations.AlterModelOptions(
            name='tzrow',
            options={'verbose_name': 'ТЗ: Строка', 'verbose_name_plural': 'ТЗ: Строки'},
        ),
    ]
