# Generated by Django 4.1.2 on 2022-11-08 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_smeta_tz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smetarowstatwords',
            options={'ordering': ['-percent'], 'verbose_name': 'Смета:Расширенная строка (тэги)', 'verbose_name_plural': 'Смета: Расширенные строки (тэги)'},
        ),
    ]
