# Generated by Django 4.1.2 on 2022-11-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sn_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sn',
            name='json_data',
            field=models.TextField(blank=True, null=True, verbose_name='JSON'),
        ),
    ]
