# Generated by Django 4.1.2 on 2022-11-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_sn_json_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sn',
            name='json_data',
        ),
    ]
